apiVersion: apps/v1
kind: Deployment
metadata:
  name: diffaction-files-service-deployment
  labels:
    app: diffaction-files-service
    name: diffaction-files-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diffaction-files-service
  template:
    metadata:
      labels:
        app: diffaction-files-service
    spec:
      containers:
        - name: diffaction-files-service
          image: artemowkin/diffaction-files-service:latest
          ports:
            - containerPort: 8000
              name: web
          command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--log-level", "debug"]
          env:
            - name: RUN_MODE
              value: stage
            - name: S3_ENDPOINT_URL
              value: https://s3.timeweb.cloud
            - name: S3_BUCKET_NAME
              value: 3acc250c-5753dc83-1a8d-41ad-956d-ababb253e7e4
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: files-service-credentials
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: files-service-credentials
                  key: aws_secret_access_key
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: users-service-credentials
                  key: secret_key
            - name: SIGNATURE_KEY
              valueFrom:
                secretKeyRef:
                  name: files-service-credentials
                  key: signature_key

            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: files-service-credentials
                  key: sentry_dsn
