apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chack-files-service-ingress
  labels:
    app: chack-files-service
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - stage.chack-check.ru
    secretName: letsencrypt
  rules:
  - host: stage.chack-check.ru
    http:
      paths:
      - path: /api/v1/files
        pathType: Prefix
        backend:
          service:
            name: chack-files-service
            port:
              number: 8000
