apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: diffaction-files-service-ingress
  labels:
    app: diffaction-files-service
  annotations:
    cert-manager.io/issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/proxy-body-size: 10240m
spec:
  ingressClassName: nginx
  tls:
  - hosts:
      - stage.diffaction.com
    secretName: diffaction-tls
  rules:
  - host: stage.diffaction.com
    http:
      paths:
      - path: /api/v1/files
        pathType: Prefix
        backend:
          service:
            name: diffaction-files-service
            port:
              number: 8000
